### ISSUE TITLE
How I can test a POST method

### ISSUE THREAD

**Issue by brunoksato** [lucasconstantino/now-we-test#5]
I was looking at the code and I can't saw nowhere the method `send` of supertest lib, I guess without that it is not possible to test the POST method right? Can you provide some examples how do you test the POST methods?

Thanks for advance.

**Comment by lucasconstantino** [comment]
It should already be working:

https://github.com/lucasconstantino/now-we-test/blob/master/tests/commands/serve.test.js#L59

https://github.com/lucasconstantino/now-we-test/blob/master/lib/commands/serve.js#L49

**Comment by paraboom** [comment]
Yep, agree, it's impossible to test `POST` lambda requests.
@lucasconstantino in your tests you have cases for non-existing `POST` requests, but nothing with real data.

**Comment by jrusk** [comment]
Thanks for the tool! I can't seem to POST either. I tried the following simple code and it runs fine on Now v2 but hangs when I run `now-we-test serve`.

```
// index.html
const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const app = new Koa();
app.use(bodyParser());
app.use(function(ctx) {
  const body = ctx.request.body;
  console.log(body);
  ctx.type = 'text/plain';
  ctx.body = `You sent: ${body}`;
});
module.exports = app.callback();

// package.json 
{
  "dependencies": {
    "koa": "^2.7.0",
    "koa-bodyparser": "^4.2.1"
  }
}

// now.json 
{
  "version": 2,
  "name": "koa-post",
  "builds": [{ "src": "index.js", "use": "@now/node" }],
  "routes": [{ "src": "/(.*)", "dest": "/index.js" }]
}
```

**Comment by lucasconstantino** [comment]
Guys, I sincerely wanna help... but so far I couldn't reproduce that locally! Check this out:

https://www.useloom.com/share/4dbb4b9754394a009ee2da6ffebe3bac

**Comment by lucasconstantino** [comment]
Can anyone create a repo with this reproduction?

**Comment by jrusk** [comment]
Here's a repo. Hopefully it helps. https://github.com/jrusk/now-koa-post

**Comment by lucasconstantino** [comment]
@jrusk @paraboom @brunoksato ok, I think I fixed the issue... it's release under `0.9.0`, do you guys mind to try?

Anyway, the problem wasn't with POST request themselves, but any request sending a body stream! I'm not really happy with all the manual delegation of request I'm having to do behind the scenes. Sorry for the inconvenience folks!

**Comment by paraboom** [comment]
@lucasconstantino thank you very much for that tool and for reacting so quickly. I'll check the new version today.

**Comment by paraboom** [comment]
@lucasconstantino it works. Thank you! 👍

**Comment by brunoksato** [comment]
Thanks @lucasconstantino but I did my own solution.
