### ISSUE TITLE
Add Regex Notes

### ISSUE THREAD

**Issue by agstover** [lucasconstantino/now-we-test#7]
Would totally understand if you don't want to bother with this, but  for those of us not well versed in Regex  would it be possible to add //comments in the code explaining what's happening here. Or maybe just comments here if you don't want them in the code. Thank you!

Found in lib/commands/serve.js

`req.url.match(new RegExp(`^${src.replace(/\(\?<[a-z]+>/, '(')}$`))`

`dest.replace(new RegExp('\\$' + id), `$+{${id}}`)`

**Comment by lucasconstantino** [comment]
I'll try and document it better, but basically JavaScript has a limited (or say, specific) Regex implementation, and I found out Now.sh route matching and redirecting system uses an upper-set not supported on JavaScript by default. I looked for a Regex lib which seemed to support what Now.sh does, but only found a _similar_ one, so my work here was "translate" the Now.sh regexes format to the ones the lib I found could understand and work with. Pretty lame work, honestly, but as long as Now.sh keeps theirs execution servers in a black box we can only guess what they do ;)

**Comment by agstover** [comment]
Ok, I see what's happening I think

Example: This url path from Zeit examples "/users/(?<id>[^/]*)" has a syntax for a certain kind of Regex, but in order to use javascript's matching/replace features it needs to be modified a bit. So, 

`let src = "/users/(?<id>[^/]*)"`
`src.replace(/(?<[a-z]+>/, '(')` becomes `"/users/([^/]*)"`
and `"/users/([^/]*)"` when put through new RegExp becomes `/^\/users\/([^\/]*)$/`
which would match against pathname `/users/123`

**Comment by lucasconstantino** [comment]
Yep... basically JavaScript does not support [*Named Capturing Groups*](https://www.regular-expressions.info/named.html) nor named backreferences. [`named-regexp-groups`](https://github.com/commenthol/named-regexp-groups/) does support it, but requires a slightly different syntax for named backreference. I translate from Now.sh pattern to the one this lib uses ;)
