### ISSUE TITLE
Routes.find() produces wrong route.

### ISSUE THREAD

**Issue by agstover** [lucasconstantino/now-we-test#8]
Here is a JSFiddle of the event.

https://jsfiddle.net/5n0whef7/1/

Essentially in the serve.js file, it's looping through my routes, finds a matching route, and then returns the route after the matching route as the value.

If the req.url is "/api/auth", then the right route is returned. If the req.url is "/api/auth/signin", then the .find() function returns the wrong value.

**Comment by agstover** [comment]
Discovered that if I made the route mapping: 
`{ "src": "/api/auth/signin", "methods": ["GET"], "dest": "/api/services/auth/index.js" }`
then it would resolve correctly. I have an express router at /api/services/auth, and so I was thinking that you could just route any request to /api/auth to that router, but apparently you have to be very explicit with the request route you map against.

**Comment by lucasconstantino** [comment]
@agstover I don't really want to decide anything on this kind of regard - I try to follow what Now servers would do. Do you mind to try the first setup you had and see if it would work as you initially expected? If that's the case, my lib has a bug ;)
